<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFZGmHrX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFZGmHrX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFZGmHrX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFZGmHrX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFZGmHrX\App_KernelDevDebugContainer([
    'container.build_hash' => 'FZGmHrX',
    'container.build_id' => '3f2c701a',
    'container.build_time' => 1632976853,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFZGmHrX');
