<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0Ab76S7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0Ab76S7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0Ab76S7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0Ab76S7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0Ab76S7\App_KernelDevDebugContainer([
    'container.build_hash' => '0Ab76S7',
    'container.build_id' => '286d5634',
    'container.build_time' => 1633304784,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0Ab76S7');
