<?php

namespace ContainerERRENzm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZhXQo5mService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zhXQo5m' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zhXQo5m'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authService' => ['privates', 'App\\Api\\Utils\\AuthService', 'getAuthServiceService', true],
        ], [
            'authService' => 'App\\Api\\Utils\\AuthService',
        ]);
    }
}
