<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVl6r6xI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVl6r6xI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVl6r6xI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVl6r6xI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVl6r6xI\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vl6r6xI',
    'container.build_id' => '3f54bf07',
    'container.build_time' => 1632982299,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVl6r6xI');
