<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'app_api_test_index' => [[], ['_controller' => 'App\\Api\\Controller\\TestController::index'], [], [['text', '/api/v1/test/']], [], []],
    'app_api_test_users' => [[], ['_controller' => 'App\\Api\\Controller\\TestController::users'], [], [['text', '/api/v1/test/users']], [], []],
    'app_core_default_index' => [[], ['_controller' => 'App\\Core\\Controller\\DefaultController::indexAction'], [], [['text', '/']], [], []],
];
